### ISSUE TITLE
[FEAT] Project부분 UI 완성

### ISSUE THREAD

**Issue by HyomK** [gyeyoonStudy/frontend#10]
| 구분        | 제목                    |
| ----------- | ----------------------- |
| [FEAT] | Project  UI 완성 |

## 이슈 분류

- [X] STYLE

## 설명

- Project => Home, Detail , Invitation, Crew 페이지 ui 완성

## ToDo

- [x] 프로젝트 생성 페이지
- [x] 초대확인 페이지
- [x] 내프로젝트 페이지
- [x] 프로젝트 생성페이지
- [x] 프로젝트 홈화면에서 Progress  부분 구현하기
- [x] Kanban Board 구현하기
- [x] Task 생성페이지 만들기
- [x] Date picker custom 구현하기
- [x] Task modal 구현하기
- [x] 팀원관리 페이지
