### ISSUE TITLE
[STYLE] Task 부분 UI 완성 

### ISSUE THREAD

**Issue by HyomK** [gyeyoonStudy/frontend#11]
## 제목 양식

| 구분        | 제목                    |
| ----------- | ----------------------- |
| [STYLE] | Task 부분 UI 완성 |

## 이슈 분류
- [X] STYLE

## 설명

- 프로젝트 홈화면 구현 및 Task UI완성

## ToDo

- [x] 프로젝트 홈화면에서 Progress  부분 구현하기
- [x] Kanban Board 구현하기
- [x] Task 생성페이지 만들기
- [x] Date picker custom 구현하기
- [x] Task modal 구현하기
