### ISSUE TITLE
[FIX] 불필요한 코드 삭제 및 수정

### ISSUE THREAD

**Issue by HyomK** [gyeyoonStudy/frontend#6]
## 제목 양식

| 구분        | 제목                    |
| ----------- | ----------------------- |
| [FIX] | 불필요한 코드 삭제 및 수정 |

## 이슈 분류

- [x] FIX

## 설명

- 작성된 코드 중 사용하지 않는 코드와 파일들을 삭제한다

## ToDo

- [x] 선언했지만 호출되지 않은 함수들, 불필요한 함수들 삭제
- [x] 테스트용 파일 삭제
- [x] public assets 폴더 정리

**Comment by HyomK** [comment]
commit이 꼬여서 올라간 순서가 이상하네요.. ㅜ
