### ISSUE TITLE
[FEAT] Sidebar 기능 구현

### ISSUE THREAD

**Issue by HyomK** [gyeyoonStudy/frontend#7]
## 제목 양식

| 구분        | 제목                    |
| ----------- | ----------------------- |
| [FEAT] | Sidebar 기능 구현 |

## 이슈 분류

- [x] FEAT

## 설명

- sidebar가 페이지 전환 시 닫히지 않는 문제 해결
- sidebar 메뉴 리스트 작성 , 라우팅 연결하기

## ToDo

- [x] 페이지 전환 시에 자동으로 sidebar 닫히는 기능 구현
- [x] sidebar 안쪽으로 들어갈 때도 애니메이션 추가
- [x] sidebar 아이템 추가 후 라우팅 연결
